cmake: fix 'undefined reference to __wrap_memcpy' in certain very specific configurations
    The issue seems to appear in the very specific case where:
      - We're linking an executable against custom build boost program_options
      - In non-release configuration, ie CFLAGS != -O2
      - We're linking the executable statically against libstdc++ using
        the -static-libstdc++ gcc flag

    The cause of this linking error is unknown, but adding -lstdc++ on the command
    line to gcc during linking seems to be a good enough work-around.